import ClientSidebar from "@/components/patient/sidebar/ClientSidebar";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function PatientDashboard({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <div className="flex ">
      <ClientSidebar />
      <div className="bg-[#f4f7fa] w-full h-screen overflow-auto">
        {children}
      </div>
    </div>
  );
}
